# This file was auto-generated by Fern from our API Definition.

import enum
import typing

T_Result = typing.TypeVar("T_Result")


class RenderMarkdownMode(str, enum.Enum):
    """
    The rendering mode.
    """

    MARKDOWN = "markdown"
    GFM = "gfm"

    def visit(self, markdown: typing.Callable[[], T_Result], gfm: typing.Callable[[], T_Result]) -> T_Result:
        if self is RenderMarkdownMode.MARKDOWN:
            return markdown()
        if self is RenderMarkdownMode.GFM:
            return gfm()
