name: Build README and deploy Datasette

on:
  workflow_dispatch:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
      # We need full history to introspect created/updated:
      with:
        fetch-depth: 0
        path: main
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.11
    - name: Install Vercel CLI
      run: npm install --global vercel@latest
    - uses: actions/cache@v2
      name: Configure pip caching
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}-v2
        restore-keys: |
          ${{ runner.os }}-pip-v2
    # - name: Cache Playwright browsers
    #   uses: actions/cache@v3
    #   with:
    #     path: ~/.cache/ms-playwright/
    #     key: ${{ runner.os }}-browsers
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r main/requirements.txt
    # - name: Install Playwright dependencies
    #   run: |
    #     shot-scraper install
    # - name: Download previous database unless REBUILD in commit message
    #   if: |-
    #     !contains(github.event.head_commit.message, 'REBUILD')
    #   run: curl --fail -o main/notes.db https://s3.amazonaws.com/note.simonwillison.net/notes.db
    #   continue-on-error: true
    - name: Build database
      run: |-
        cd main
        python build_database.py
    # - name: Soundness check
    #   run: |-
    #     cd main
    #     datasette . --get / | grep "Simon Willison: TIL"
    # - name: Generate missing screenshots
    #   env:
    #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #   run: |-
    #     cd main
    #     python generate_screenshots.py
    #     sqlite-utils vacuum notes.db
    # - name: Update README
    #   run: |-
    #     cd main
    #     python update_readme.py --rewrite
    #     cat README.md
    # - name: Commit and push if README changed
    #   run: |-
    #     cd main
    #     git diff
    #     git config --global user.email "actions@users.noreply.github.com"
    #     git config --global user.name "README-bot"
    #     git diff --quiet || (git add README.md && git commit -m "Updated README")
    #     git push
    # - name: Upload latest notes.db to the S3 bucket
    #   env:
    #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #   run: |-
    #     s3-credentials put-object note.simonwillison.net notes.db main/notes.db
    - name: Deploy Datasette using Vercel
      env:
        NOW_TOKEN: ${{ secrets.NOW_TOKEN }}
      run: |-
        cd main
        datasette publish vercel notes.db \
          --token $NOW_TOKEN \
          --project kevin-weblog \
          --metadata metadata.yaml \
          --static static:static \
          --install datasette-template-sql \
          --install "datasette-sitemap>=1.0" \
          --install "datasette-atom>=0.7" \
          --install datasette-json-html \
          --install beautifulsoup4 \
          --install "datasette-debug-asgi>=1.1" \
          --install "datasette-graphql>=2.2" \
          --install datasette-block-robots \
          --plugins-dir plugins \
          --template-dir templates \
          --public \
          --debug